# Generated by Django 5.0.2 on 2024-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text="13 character <a href='https://www.isbn-international.org/content/what-isbn'>ISBN number </a>", max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
